### ISSUE TITLE
Stash Support

### ISSUE THREAD

**Issue by nguyen-tim** [czechboy0/Buildasaur#105] opened 2015-07-21 22:08 UTC
Hi czechboy0,

Great job creating this tool. I ran into a small issue when trying to configure my project with Buildasaur.  Our repos have moved from Github to Stash and I was wondering if Buildasaur will support stash projects in the future.  This alert pops up when trying to add my Xcode project:

Couldn't add Xcode project at path file:///nameOfProject.xcworkspace, error: Disallowed checkout type, the project must be checked out over one of the supported schemes: SSH.

Any information will be greatly appreciated.

**Comment by czechboy0** [comment] 2015-07-21 22:14
Hi @nguyen-tim, thanks!

At the moment, Buildasaur only supports GitHub. It's because each service has a very specific API when it comes to managing Pull Requests. We also have a request for Bitbucket (#65), so I'll consider this a request for another service.

However, I imagine the only way this will be done is if someone using Stash and understanding lots of the expected behaviors steps in and helps out by writing a lot of the code. Technically, a lot of code should be shareable with the GitHub code, but I just haven't done this yet.

**Comment by czechboy0** [comment] 2015-10-16 12:01
AFAIU, Stash is now called Bitbucket Server, so hopefully they'll have the same API as cloud Bitbucket. This this is a duplicate of #65.

**Closed as completed by czechboy0** 2015-10-16 12:01 UTC
Labels: feature-request
