### ISSUE TITLE
Add PR Title to Bot Name

### ISSUE THREAD

**Issue by grantjk** [czechboy0/Buildasaur#187] opened 2015-10-21 01:00 UTC
The PR number is helpful, obviously, but it still requires me to look at Github to find out which bot I'm actually interested in. I'd like to be able to look at Xcode and find the bot that corresponds to the branch I'm working on without having to go look for the PR number.

**Comment by czechboy0** [comment] 2015-10-21 12:19
Duplicate of #23. See the conversation there why it's not a trivial change.

**Closed as completed by czechboy0** 2015-10-21 12:19 UTC
