### ISSUE TITLE
Update UI to support multiple repositories

### ISSUE THREAD

**Issue by joelekstrom** [czechboy0/Buildasaur#72] opened 2015-06-16 08:20 UTC
I have some ideas for how the UI should look in Buildasaur. Right now it looks very crammed, lots of info that doesn't really need to be shown. I started working on migrating it to how I would like it to look, but I won't put too much work until I know what direction @czechboy0 wants to take.

Anyway, I've used the OS X user settings pane as a basic guide:

![skarmavbild 2015-06-16 kl 10 11 34](https://cloud.githubusercontent.com/assets/1607453/8178635/65d27b8c-1410-11e5-8692-163820f8899a.png)

In Builda, this roughly translates to having a list of repos on the left side, and +/- buttons to add/remove them as needed.

What's more important is the right side. Right now, the Builda UI shows 3 different things on the main screen - project setup, server setup and console/running status. These 3 things should be 3 different top tabs in the new UI. No need to show them all at once, and it will make a much more pleasant and light default view.

Builda is also showing a bunch of settings buttons today, which really could go in an advanced settings page for the repo. Maybe something like the gear in the list to the left in the example above.

@czechboy0 What do you think? Is this a direction you'd like the Buildasaur UI to take?

**Comment by czechboy0** [comment] 2015-06-16 09:01
Absolutely. I actually have someone helping me with creating a completely new design for Buildasaur that would solve all the issues you just mentioned. It's being worked on and is conceptually pretty similar to what you're suggesting here :) 

I'll post wireframes once I have them!

**Comment by joelekstrom** [comment] 2015-06-16 09:14
Nice :+1:

**Comment by czechboy0** [comment] 2015-06-16 09:46
Sort of duplicate of #12.

**Closed as completed** 2015-06-16 09:53 UTC
