### ISSUE TITLE
Allow customizations of the Bot name

### ISSUE THREAD

**Issue by st3fan** [czechboy0/Buildasaur#64] opened 2015-05-26 15:13 UTC
Right now when I go to the Xcode Server web site (where you can download/install integration builds), it shows me a long list of bots that all look like:

```
BuildaBot [mozilla/firefox-ios] PR #498
```

I would like to customize this name so that it shows something like:

```
PR #409 Do not stop system audio on start
```

(I don't care about the repo name or the BuildaBot static string).

Ideally this can be configured with some really simple template string like `PR #{{PR_NR}} {{PR_TITLE}}` so that people can customize in different ways?

**Comment by czechboy0** [comment] 2015-05-26 15:14
Duplicate of #29.

**Comment by czechboy0** [comment] 2015-05-26 15:16
@st3fan The only issue with taking out the name of the repo is that bots might clash if you're running multiple projects on the same Xcode Server. Builda uses the bot's name to uniquely identify it. 

I'll look into a good way of allowing what you want to do though :)

**Comment by czechboy0** [comment] 2015-06-16 04:57
Closing as this is a duplicate of #29.

**Closed as completed by czechboy0** 2015-06-16 04:57 UTC
Labels: duplicate
