### ISSUE TITLE
Buildasaur get confused when creating multiple PR from the same branch

### ISSUE THREAD

**Issue by valeriomazzeo** [czechboy0/Buildasaur#94] opened 2015-07-16 15:25 UTC
Consider the following scenario:

feature/1234 -> to merge into -> develop
feature/1234 -> to merge into -> release

Buildasaur create two different Xcode server bots, one for each PR.

When the first bot runs, everything is ok
When the second one start integrating, the first PR start writing many comments (repeated) and also the build status keep changing reflecting the status of the second bot.

It looks like buildasaur get confused because of the source branch being the same.

**Comment by czechboy0** [comment] 2015-07-16 15:54
This looks like a bug, thanks for reporting! :+1: 
 (Shhh, I haven't tested this case at all, so it's very possible it's broken.)

**Comment by valeriomazzeo** [comment] 2015-07-16 15:57
it looks like every time buildasaur launch a check (15s) it posts a new comment.

**Comment by czechboy0** [comment] 2015-07-16 16:00
Are you running Buildasaur from code and built locally or are you using a .app from a release here on GitHub?

**Comment by valeriomazzeo** [comment] 2015-07-16 16:03
I am using the app. 0.29 I think?

It's the latest you can download.

**Comment by czechboy0** [comment] 2015-07-16 21:01
Okay, this is amazing. Such an interesting bug. Let me try to explain what is going on.

Let me explain the context:
GitHub's Statuses are _only_ attached to **commits**, not to branches or pull requests. That means that if you have one branch as the head of two pull requests, both the pull requests will share the status (the little _failing_ - red x, _success_ - green checkmark and _pending_ - yellow dot status icons). This is due to how GitHub treats code (it makes sense) - assuming you test code in one commit, and it succeeds, it's a piece of valid code. Doesn't matter how many PRs you create from it, it's always going to have the same status.

Now, Buildasaur uses the GitHub status **disparity** as a signal to post a comment or correct the status. Meaning that if our bot says the integration succeeds, we know it should be a _success_ status on GitHub. If GitHub doesn't have a status on that commit yet, we post it. If it has a different one (like _failure_ or _pending_), we post a change and also post a comment. 

In short, whether a comment is posted and a new status set _depends on the current status on GitHub_. If it's already what it's supposed to be (e.g. we say it should be _success_ and it already is on GitHub, we don't post anything).

Here comes the fun: when you have _two pull requests_, Builda creates two bots. Simple as that. But if those bots are on the **same branch** (btw, IMHO, having two PRs on the same branch is a strange git practice, but that's for a different discussion), the status of the commit will be set based on the last bot that tested on a branch with that commit. So basically these two bots and PRs are fighting over the status of that commit. Let's say bot A is running, it will try to set the commit's (and thus PR "A"'s) status to _pending_. But, at the same time, bot B already finished with success, so it wants to make sure the status is _success_. So they, in an arbitrary order, will change the status to what they want. Until the next sync, when the fight is all anew. And since, whenever a bot is finished and the GitHub status **doesn't match**, Builda posts a comment, you get those extra comments **until both bots have finished running**.

This "bug" is really an unfortunate outcome of the fundamental principles of GitHub, Xcode Server and Buildasaur. I can't think of an easy way to fix this at the moment, but be sure that I won't rest until I can prevent Builda from going crazy like this. This is a very interesting bug and thanks a lot for reporting this.

So - I'm sorry that you're having this issue. What I'd suggest in the meantime is to avoid having more than one PR from one branch **at the same time**. If you can first open one, test it, merge it, then open the other, that will work fine. (Obviously you can continue to have any number of PRs open at the same time, assuming they're all on a different branch.)

Hope you at least got the gist of what the issue is, if not, I'll try to rephrase the explanation :)

**Comment by valeriomazzeo** [comment] 2015-07-16 22:07
@czechboy0 thanks for looking into this, it's absolutely crystal clear. Unfortunately, the scenario is not that uncommon if you think about tools like Travis that not only test the branch, but instead they tests the resulting merged branch. In that case, in fact, the results of the two different integrations may differ (I mentioned that workflow on twitter already).

Just to make sure I understood it properly.
GitHub doesn't set the status on PRs but on Commits instead. Therefore, you are saying that there is no way to have buildasaur (on each sync) to change the status of a PR. Assuming this is true, there is not much you can do.

It's a fun problem, isn't it?

I can see the workaround for the moment to not create pull requests from the same commit at the same time :+1:

**Comment by czechboy0** [comment] 2015-07-16 22:35
> but instead they tests the resulting merged branch. In that case, in fact, the results of the two different integrations may differ

I get it, but unfortunately this doesn't have much to do with Buildasaur, because AFAIK, Xcode Server does a normal `git clone`, which doesn't pull these _merge_ branches from GitHub. There's nothing I can do :( ([mentioned Twitter conversation](https://twitter.com/buildasaur/status/621715201373642752))

> Therefore, you are saying that there is no way to have buildasaur (on each sync) to change the status of a PR.

That's not the problem, rather we'd like to be able to decouple the status of the head commit of each PR, so that we can set their status separately. Since it's shared, the PRs start getting confused as well, because "someone" is changing their status under their hand - and when that happens and the build is done, we post a comment.

**Comment by valeriomazzeo** [comment] 2015-07-16 22:40
That's what I meant. Changing the status of a PR by id and not implicitly by the commit that basically may change multiple PR's statuses at once.

**Comment by czechboy0** [comment] 2015-07-17 00:00
Yeah exactly. Unfortunately that's not possible :(

**Comment by czechboy0** [comment] 2015-07-17 19:50
Well, anyway. I don't know how to fix this without completely changing the fundamentals of how Buildasaur works. Buildasaur is stateless right now, which means that it doesn't persist any data between syncs (which happen every 15 seconds by default). So everything it does when deciding what to do with each PR and Bot, it needs to read from GitHub and Xcode Server, respectively. It can't just "save" that it "already posted a comment" and not do it again, because you could stop Buildasaur and start it again, and that information wouldn't be there again (and persisting would bring another layer of complexity). I wanted to make sure that even if you restart Buildasaur at **any** moment and it runs on **any** machine, everything works as expected. Right now it doesn't matter if you stop Buildasaur on one machine and start on another, it will do the right thing. If we saved data to the local Buildasaur, this wouldn't be the case anymore. Which I'm not willing to give up unless there's a very good reason.

I understand that this particular case is not in any way working _as expected_, but the way GitHub treats statuses just makes it very difficult to change.

I will _not_ make any changes right now. If I, or anyone else, can think of a reasonable way to minimize the damage caused in this case (extra comments in PRs), please comment here. Otherwise, I'm closing this as a _won't fix_ for now.

**Closed as completed by czechboy0** 2015-07-17 19:51 UTC
Labels: bug, investigate, wontfix, help needed
